name: Bug Report
description: Report a bug in Math Blast
title: "[BUG] "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the form below.

  - type: input
    id: version
    attributes:
      label: Math Blast Version
      description: What version are you using? (e.g., v1.0, v1.1)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Clear description of what the bug is
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: |
        Steps to reproduce the behavior:
        1. Start game
        2. Go to...
        3. Click...
        4. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should happen?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error logs or screenshots
      description: Add error messages or screenshots

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I've checked for existing issues
          required: true
        - label: This happens on latest version
          required: true
