name: Feature Request
description: Suggest a new feature for Math Blast
title: "[FEATURE] "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Great ideas are welcome! Please describe your feature request.

  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: What feature would you like to see?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature useful? What problem does it solve?
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation ideas
      description: How could this be implemented?

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I've checked for existing feature requests
          required: true
